---
title: Get started with the jfa package
author: Koen Derks
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{Get started with the jfa package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteDepends{jfa}
  %\VignetteKeywords{audit, jfa}
  %\VignettePackage{jfa}
  %\VignetteEncoding{UTF-8}
---

## Introduction

Welcome to the 'Get started' page of the **jfa** package. **jfa** is an R
package that provides Bayesian and classical statistical methods for audit
sampling, data auditing, and algorithm auditing. This page points you to the
vignettes accompanying each of these three subjects.

## Audit sampling

Firstly, **jfa** facilitates statistical audit sampling. That is, the package
provides functions for planning, performing, and evaluating an audit sample
compliant with international standards on auditing.

- [Audit sampling: Get started](https://koenderks.github.io/jfa/articles/audit-sampling.html)
- [Creating a prior distribution for audit sampling](https://koenderks.github.io/jfa/articles/creating-prior.html)
- [Planning statistical audit samples](https://koenderks.github.io/jfa/articles/sample-planning.html)
- [Selecting statistical audit samples](https://koenderks.github.io/jfa/articles/sample-selection.html)
- [Evaluating statistical audit samples](https://koenderks.github.io/jfa/articles/sample-evaluation.html)
- [Evaluating audit samples with partial misstatements](https://koenderks.github.io/jfa/articles/sample-evaluation-partial.html)
- [Walkthrough of the classical audit sampling workflow](https://koenderks.github.io/jfa/articles/sampling-workflow.html)
- [Walkthrough of the Bayesian audit sampling workflow](https://koenderks.github.io/jfa/articles/bayesian-sampling-workflow.html)

## Data auditing

Secondly, **jfa** facilitates statistical data auditing. That is, the package
includes functions for auditing data, such as testing the distribution of first
digits of a data set against Benford's law, or assessing whether a data set
includes an unusual amount of repeated values.

- [Data auditing: Get started](https://koenderks.github.io/jfa/articles/data-auditing.html)
- [Digit analysis](https://koenderks.github.io/jfa/articles/digit-analysis.html)

## Algorithm auditing

Finally, **jfa** facilitates statistical algorithm auditing. That is, the
package implements functions for auditing algorithms, such as computing fairness
metrics and testing the equality of parity metrics across protected groups.

- [Algorithm auditing: Get started](https://koenderks.github.io/jfa/articles/algorithm-auditing.html)
- [Algorithmic fairness](https://koenderks.github.io/jfa/articles/model-fairness.html)
