# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("inflated_beta", "inflated_poisson", "or_fairness", "pp_error", "pp_taint")

# load each stan module
Rcpp::loadModule("stan_fit4inflated_beta_mod", what = TRUE)
Rcpp::loadModule("stan_fit4inflated_poisson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4or_fairness_mod", what = TRUE)
Rcpp::loadModule("stan_fit4pp_error_mod", what = TRUE)
Rcpp::loadModule("stan_fit4pp_taint_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if (dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
    allow_undefined = TRUE,
    obfuscate_model_name = FALSE
  )
  stanfit$model_cpp <- list(
    model_cppname = stanfit$model_name,
    model_cppcode = stanfit$cppcode
  )
  # create stanmodel object
  methods::new(
    Class = "stanmodel",
    model_name = stanfit$model_name,
    model_code = stanfit$model_code,
    model_cpp = stanfit$model_cpp,
    mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name))
  )
})
