on: workflow_dispatch

name: Update package statistics

jobs:
  update:
    name: Update package statistics
    runs-on: windows-latest
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.5'
      - uses: r-lib/actions/setup-pandoc@v1

      # Install required packages and update README
      - name: Install required packages and render README
        run: |
          install.packages(c("remotes", "rmarkdown", "cranlogs", "lubridate", "plyr", "ggplot2", "scales", "maptools", "installr", "data.table", "svglite"))
          rmarkdown::render("README.Rmd")
        shell: Rscript {0}

      # Make sure only the images and data set are committed
      - name: Remove README.html
        run: |
          git add .
          git rm -f README.md
          git rm -f README.html

      # Create a pull request with changes to master
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update package statistics
          signoff: false
          branch: stats-update
          delete-branch: true
          title: 'Update package statistics'
          body: |
            Daily update for the `jfa` package statistics
            - Updated with *today's* downloads from [cranlogs][1]
            - Auto-generated by [jfa][2]

            [1]: https://cranlogs.r-pkg.org/
            [2]: https://github.com/koenderks/jfa
          labels: |
            automated pr
          reviewers: koenderks
          draft: false

      # Check outputs of workflow
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"