on: workflow_dispatch

name: Update package statistics

jobs:
  update:
    name: Update package statistics
    runs-on: windows-latest
    steps:
      
      # Step 1: Checks-out the jfa repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      # Step 2: Get the current date for the PR name
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Step 3: Install required packages
      - name:  Install required packages
        run: |
          install.packages(c("cranlogs", "lubridate", "plyr", "ggplot2", "scales", "maptools", "installr", "data.table", "svglite"))
        shell: Rscript {0}

      # Step 4: Render relevant data and figures
      - name: Render relevant data and figures
        run: |
          source("man/figures/render-figures.R")
        shell: Rscript {0}

      # Step 5: Create a pull request with the updated data and figures to master
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Package statistics update for ${{ steps.date.outputs.date }}
          signoff: false
          branch: stats-update
          delete-branch: true
          title: 'Package statistics update for ${{ steps.date.outputs.date }}'
          body: |
            Daily update for the `jfa` package statistics
            - Updated with *today's (${{ steps.date.outputs.date }})* downloads from [cranlogs][1]
            - Auto-generated by [jfa][2]

            [1]: https://cranlogs.r-pkg.org/
            [2]: https://github.com/koenderks/jfa
          labels: |
            automated pr
          reviewers: koenderks
          draft: false

      # Step 6: Check the output of the workflow
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"